files:
    include: 'src/**/*.s+(a|c)ss'
rules:
    indentation:
        - 2
        - size: 4
    quotes:
        - 2
        - style: single
    brace-style:
        - 2
        - style: '1tbs'
    final-newline:
        - 2
    no-trailing-whitespace:
        - 2
    space-after-comma:
        - 2
    space-after-colon:
        - 2
    space-before-brace:
        - 2
    space-before-bang:
        - 2
    empty-line-between-blocks:
        - 2
    single-line-per-selector:
        - false

