language: node_js
node_js:
  - "6"

cache:
    directories:
        - .nvm

before_install:
    - ./scripts/travis/lint.sh

install:
    - ./scripts/travis/install.sh

script:
    - ./scripts/travis/build.sh
    - ./scripts/travis/test.sh
